title: Alix Naugler

description: |
  <img src="/assets/alix.jpg" alt="Alix Naugler" style="border-radius: 50%; width: 130px; margin-bottom: 15px;" />

  I am a PhD student in the Applied Economics and Management program at Cornell University.  
  My research lies at the intersection of development, industrial organization, and agricultural economics.  
  I study how policy and market dynamics shape firm behavior, farmer beliefs, and economic outcomes in developing economies.

  [CV](/assets/CV_AlixNaugler_2025.pdf)  
  ann@cornell.edu

remote_theme: orderedlist/minimal
