title: Alix Naugler
description: PhD Student in Applied Economics & Management, Cornell University
ann@cornell.edu | [CV](/assets/CV_AlixNaugler_2025.pdf)

remote_theme: orderedlist/minimal

---

I am a third-year PhD student in the Applied Economics and Management program at Cornell University. My research lies at the intersection of development, industrial organization, and agricultural economics. I study how policy and market dynamics shape firm behavior, farmer beliefs, and economic outcomes in developing economies.

---
