theme: jekyll-theme-minimalist
title: Alix Naugler
description: PhD student in Applied Economics & Mangement

author:
  avatar: "/assets/alixnaugler.jpg"
  name: "Alix Naugler"
  emloer: "Cornell University"
  email: "ann@cornell.edu"
